#!/bin/bash

#make sure number of arguments are correct
if [ ! $# -eq 6 ]
then
	echo 'Execute program by format:'
	echo 'sh execution field_snapshot_scale initial_separation particle_number timesteps delta_time initial_conditions'
	echo 'initial condition options: random, random_2_clumps'
	exit
fi

#compile and run the fortran particle simulator
gfortran physics.f95 particle_sim.f95 -o particle
./particle $2 $3 $4 $5 $6

#compile and run the python plotter
python python_plotter.py $1 $3 $4 $5 $6
